<?php
/**
 * CloudScale shared Telegram notification helper.
 *
 * Credentials are stored under shared wp_options keys so any CloudScale plugin
 * that includes this file can send and configure Telegram without duplicating logic.
 *
 * DO NOT EDIT THIS FILE in individual plugin directories.
 * Edit shared-admin-ui/class-cloudscale-telegram.php and run sync-admin-css.sh.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( class_exists( 'CloudScale_Telegram' ) ) {
	return;
}

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedClassFound -- shared cross-plugin utility; CloudScale IS the brand prefix
class CloudScale_Telegram {
// phpcs:enable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedClassFound

	const OPTION_TOKEN   = 'cloudscale_telegram_bot_token'; // pragma:allow-secret
	const OPTION_CHAT_ID = 'cloudscale_telegram_chat_id';

	public static function is_configured(): bool {
		return ! empty( get_option( self::OPTION_TOKEN ) ) && ! empty( get_option( self::OPTION_CHAT_ID ) );
	}

	/**
	 * Build the alert prefix line: "{emoji} Domain : Source\nLEVEL\n\n"
	 *
	 * @param string $source  Human-readable plugin/feature name, e.g. "Backup and Restore".
	 * @param string $level   One of: info, warning, error, critical.
	 */
	private static function alert_prefix( string $source, string $level ): string {
		$host   = (string) ( wp_parse_url( home_url(), PHP_URL_HOST ) ?: '' );
		$domain = implode( '.', array_map( 'ucfirst', explode( '.', strtolower( $host ) ) ) );

		$emojis = [
			'info'     => "\u{2705}",
			'warning'  => "\u{26A0}\u{FE0F}",
			'error'    => "\u{274C}",
			'critical' => "\u{1F6A8}",
		];
		$emoji = $emojis[ $level ] ?? $emojis['info'];
		$label = strtoupper( $level ?: 'INFO' );

		$header = $source ? $domain . ' : ' . $source : $domain;
		return $emoji . ' ' . $header . "\n" . $label . "\n\n";
	}

	/**
	 * The site's own clock, with the zone named: "2026-08-05 07:02:11 SAST".
	 *
	 * wp_date() applies the timezone configured in Settings → General, and the T
	 * format character supplies the abbreviation, so the reader never has to do
	 * arithmetic or guess which zone a bare time is in.
	 *
	 * @param int|null $ts Unix timestamp; current time when null.
	 */
	public static function local_time( ?int $ts = null ): string {
		$ts   = $ts ?? time();
		$when = wp_date( 'Y-m-d H:i:s', $ts );
		// wp_date() returns false if the timezone is unusable; never let a broken
		// setting cost us the whole alert.
		if ( ! is_string( $when ) || '' === $when ) {
			return gmdate( 'Y-m-d H:i:s', $ts ) . ' UTC';
		}
		return $when . ' ' . self::tz_label( $ts );
	}

	/**
	 * The timezone label to print: a real zone abbreviation when there is one.
	 *
	 * Settings → General accepts either a named zone (Africa/Johannesburg, which
	 * makes wp_date('T') produce SAST) or a bare UTC offset. With a bare offset there
	 * IS no zone name, and wp_date('T') answers "GMT+0200" — which reads as a GMT
	 * time to anyone scanning an alert, and GMT is not what the clock is showing.
	 *
	 * An offset-shaped label is therefore resolved to a zone abbreviation, via PHP's
	 * own offset→zone table, rather than printed as "+02:00": alerts should name the
	 * clock they are quoting, and a bare offset makes the reader do the work. Several
	 * zones share an offset and PHP returns the canonical one, so the abbreviation is
	 * right for the offset even where the zone id is not the site's own — which is why
	 * the *offset* is what gets resolved and never invented from anything else. Set a
	 * named zone in Settings → General and this returns its own abbreviation directly.
	 *
	 * @param int|null $ts Timestamp the label applies to (DST-dependent zones).
	 */
	public static function tz_label( ?int $ts = null ): string {
		$ts   = $ts ?? time();
		$abbr = (string) wp_date( 'T', $ts );
		if ( preg_match( '/^(?:GMT|UTC)?\s*([+-])(\d{1,2}):?(\d{2})?$/', $abbr, $m ) ) {
			$seconds = ( (int) $m[2] * 3600 ) + ( (int) ( $m[3] ?? 0 ) * 60 );
			if ( '-' === $m[1] ) {
				$seconds = -$seconds;
			}
			// The candidate zone's offset AT THIS INSTANT must equal the offset we are
			// labelling. Without that check, +02:00 resolved to a zone whose
			// abbreviation was EEST — a real name for a clock that is +03:00 in
			// August, printed next to a time that is +02:00. A label contradicting
			// the timestamp it labels is worse than a bare offset.
			$moment     = new DateTime( '@' . $ts );
			$candidates = array();
			foreach ( array( 0, 1 ) as $dst ) {
				$guess = timezone_name_from_abbr( '', $seconds, $dst );
				if ( is_string( $guess ) && '' !== $guess ) {
					$candidates[] = $guess;
				}
			}
			// Nothing from the abbreviation table fits, so ask the zone list directly.
			$candidates = array_merge( $candidates, timezone_identifiers_list() );
			foreach ( $candidates as $zone ) {
				try {
					$tz = new DateTimeZone( $zone );
				} catch ( \Exception $e ) {
					unset( $e );
					continue;
				}
				if ( $tz->getOffset( $moment ) !== $seconds ) {
					continue;
				}
				$named = $moment->setTimezone( $tz )->format( 'T' );
				// A zone whose own label is offset-shaped puts us back where we
				// started, so keep looking.
				if ( is_string( $named ) && '' !== $named && ! preg_match( '/^(?:GMT|UTC)?[+-]/', $named ) ) {
					return $named;
				}
			}
			// Last resort: the offset, never "GMT+0200".
			return $m[1] . str_pad( $m[2], 2, '0', STR_PAD_LEFT ) . ':' . ( $m[3] ?? '00' );
		}
		return '' !== $abbr ? $abbr : 'UTC';
	}

	/**
	 * Rewrite UTC timestamps inside an alert body into the site's local zone.
	 *
	 * Alerts quote times from places that are UTC by construction — PHP's error log
	 * writes "[04-Aug-2026 20:40:15 UTC]", and several of our own messages used
	 * gmdate(). An alert that says one thing in the footer and another in the body
	 * makes the reader do timezone arithmetic at exactly the moment they can least
	 * afford to, so both are converted to the same clock.
	 *
	 * Only strings explicitly labelled UTC are touched. A time with no zone on it
	 * is left alone rather than guessed at.
	 */
	private static function localise_utc_stamps( string $text ): string {
		// PHP error-log prefix: [04-Aug-2026 20:40:15 UTC] — and GMT, which is what
		// PHP actually emits when date.timezone is UTC. Matching only "UTC" is why
		// alerts kept showing a GMT stamp after every other clock had been localised:
		// the copy was correct everywhere we controlled and wrong on the one line we
		// were quoting verbatim out of the log.
		$text = (string) preg_replace_callback(
			'/\[(\d{2}-[A-Za-z]{3}-\d{4} \d{2}:\d{2}:\d{2}) (?:UTC|GMT)\]/',
			static function ( array $m ): string {
				$ts = strtotime( $m[1] . ' UTC' );
				return false === $ts ? $m[0] : '[' . self::local_time( $ts ) . ']';
			},
			$text
		);
		// ISO-ish: 2026-08-05 02:30:01 UTC
		$text = (string) preg_replace_callback(
			'/(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2})Z?\s+(?:UTC|GMT)\b/',
			static function ( array $m ): string {
				$ts = strtotime( str_replace( 'T', ' ', $m[1] ) . ' UTC' );
				return false === $ts ? $m[0] : self::local_time( $ts );
			},
			$text
		);
		return $text;
	}

	/**
	 * Send a Telegram message. Returns true on success.
	 *
	 * @param string $text    Message body.
	 * @param string $source  Plugin/feature name shown in the header (e.g. "Backup and Restore").
	 * @param string $level   Alert level: info, warning, error, critical.
	 */
	public static function send( string $text, string $source = '', string $level = 'info' ): bool {
		$token   = trim( (string) get_option( self::OPTION_TOKEN, '' ) );
		$chat_id = trim( (string) get_option( self::OPTION_CHAT_ID, '' ) );
		if ( ! $token || ! $chat_id ) {
			return false;
		}

		// Local time on EVERY alert, stamped here rather than at ~20 call sites so a
		// new alert cannot ship without one. Times quoted inside the body are
		// converted to the same clock — see localise_utc_stamps().
		$full = self::alert_prefix( $source, $level )
			. self::localise_utc_stamps( $text )
			. "\n\n" . self::local_time();

		$response = wp_remote_post(
			'https://api.telegram.org/bot' . rawurlencode( $token ) . '/sendMessage',
			[
				'timeout' => 10,
				'headers' => [ 'Content-Type' => 'application/json' ],
				'body'    => wp_json_encode( [ 'chat_id' => $chat_id, 'text' => $full ] ),
			]
		);

		if ( is_wp_error( $response ) ) {
			return false;
		}

		return (int) wp_remote_retrieve_response_code( $response ) === 200;
	}

	/**
	 * Save shared Telegram credentials from POST data.
	 * Call from a plugin's save AJAX handler after nonce verification.
	 */
	public static function save_from_post(): void {
		// phpcs:disable WordPress.Security.NonceVerification.Missing -- caller is responsible for nonce check
		update_option( self::OPTION_TOKEN, sanitize_text_field( wp_unslash( $_POST['telegram_token'] ?? '' ) ) );
		update_option( self::OPTION_CHAT_ID, sanitize_text_field( wp_unslash( $_POST['telegram_chat_id'] ?? '' ) ) );
		// phpcs:enable WordPress.Security.NonceVerification.Missing
	}

	/**
	 * Register the shared AJAX handlers (test + fetch-chat-id).
	 * Safe to call from multiple plugins; handlers are registered only once.
	 */
	public static function register_ajax(): void {
		if ( ! has_action( 'wp_ajax_cloudscale_telegram_fetch_chat_id' ) ) {
			add_action( 'wp_ajax_cloudscale_telegram_fetch_chat_id', static function (): void {
				if ( ! current_user_can( 'manage_options' ) ) {
					wp_send_json_error( 'Forbidden', 403 );
				}
				check_ajax_referer( 'cloudscale_telegram_fetch', 'nonce' );

				$token = sanitize_text_field( wp_unslash( $_POST['telegram_token'] ?? '' ) );
				if ( ! $token ) {
					wp_send_json_error( 'Bot token is required.' );
					return;
				}

				$response = wp_remote_get(
					'https://api.telegram.org/bot' . rawurlencode( $token ) . '/getUpdates',
					[ 'timeout' => 10 ]
				);

				if ( is_wp_error( $response ) ) {
					wp_send_json_error( 'Request failed: ' . $response->get_error_message() );
					return;
				}

				$code = (int) wp_remote_retrieve_response_code( $response );
				$body = wp_remote_retrieve_body( $response );
				$data = json_decode( $body, true );

				if ( $code !== 200 || empty( $data['ok'] ) ) {
					$detail = is_array( $data ) ? ( $data['description'] ?? $body ) : $body;
					wp_send_json_error( "Telegram HTTP {$code}: {$detail}" );
					return;
				}

				if ( empty( $data['result'] ) ) {
					wp_send_json_error( 'No messages yet. Send any message to your bot on Telegram first, then try again.' );
					return;
				}

				$chat_id = null;
				foreach ( $data['result'] as $update ) {
					$chat_id = $update['message']['chat']['id']
						?? $update['channel_post']['chat']['id']
						?? $update['my_chat_member']['chat']['id']
						?? null;
					if ( $chat_id !== null ) {
						break;
					}
				}

				if ( $chat_id === null ) {
					wp_send_json_error( 'Could not find a chat ID in the updates.' );
					return;
				}

				wp_send_json_success( [ 'chat_id' => (string) $chat_id ] );
			} );
		}

		if ( has_action( 'wp_ajax_cloudscale_telegram_test' ) ) {
			return;
		}
		add_action( 'wp_ajax_cloudscale_telegram_test', static function (): void {
			if ( ! current_user_can( 'manage_options' ) ) {
				wp_send_json_error( 'Forbidden', 403 );
			}
			check_ajax_referer( 'cloudscale_telegram_test', 'nonce' );

			// phpcs:disable WordPress.Security.NonceVerification.Missing -- nonce verified above
			$token   = sanitize_text_field( wp_unslash( $_POST['telegram_token'] ?? '' ) );
			$chat_id = sanitize_text_field( wp_unslash( $_POST['telegram_chat_id'] ?? '' ) );
			$source  = sanitize_text_field( wp_unslash( $_POST['test_source'] ?? '' ) ) ?: 'Telegram';
			// phpcs:enable WordPress.Security.NonceVerification.Missing

			// Fall back to stored credentials (used by the credentials panel test button).
			if ( ! $token ) { $token   = (string) get_option( self::OPTION_TOKEN, '' ); }
			if ( ! $chat_id ) { $chat_id = (string) get_option( self::OPTION_CHAT_ID, '' ); }

			if ( ! $token || ! $chat_id ) {
				wp_send_json_error( 'Bot token and chat ID are required.' );
				return;
			}

			$prefix   = self::alert_prefix( $source, 'info' );
			$response = wp_remote_post(
				'https://api.telegram.org/bot' . rawurlencode( $token ) . '/sendMessage',
				[
					'timeout' => 10,
					'headers' => [ 'Content-Type' => 'application/json' ],
					'body'    => wp_json_encode( [ 'chat_id' => $chat_id, 'text' => $prefix . 'Test message sent successfully. Alerts are working.' ] ),
				]
			);

			if ( is_wp_error( $response ) ) {
				wp_send_json_error( 'Telegram request failed: ' . $response->get_error_message() );
				return;
			}

			$code = (int) wp_remote_retrieve_response_code( $response );
			if ( $code !== 200 ) {
				$body    = wp_remote_retrieve_body( $response );
				$decoded = json_decode( $body, true );
				$detail  = is_array( $decoded ) ? ( $decoded['description'] ?? $body ) : $body;
				wp_send_json_error( "Telegram HTTP {$code}: {$detail}" );
				return;
			}

			wp_send_json_success( [ 'msg' => 'Test message sent.' ] );
		} );
	}

	/**
	 * Render the Telegram settings card.
	 *
	 * @param string $text_domain  Unused; kept for call-site compatibility across plugins.
	 */
	public static function render_settings_fields( string $text_domain, string $source = '' ): void {
		static $js_output = false;

		$token       = esc_attr( (string) get_option( self::OPTION_TOKEN, '' ) );
		$chat_id     = esc_attr( (string) get_option( self::OPTION_CHAT_ID, '' ) );
		$test_nonce  = wp_create_nonce( 'cloudscale_telegram_test' );
		$fetch_nonce = wp_create_nonce( 'cloudscale_telegram_fetch' );
		?>
		<div style="border-radius:8px;overflow:hidden;border:1px solid #b3e5fc;">
			<div style="background:linear-gradient(135deg,#0277bd 0%,#039be5 100%);padding:8px 14px;display:flex;align-items:center;gap:8px;">
				<span style="font-size:1rem;">&#9992;</span>
				<span style="color:#fff;font-weight:700;font-size:0.9rem;"><?php echo esc_html( 'Telegram' ); ?></span>
			</div>
			<div style="padding:14px;background:#f0f9ff;">
				<p class="cs-help"><?php echo esc_html( 'Instant push to your phone. Create a bot via @BotFather on Telegram, then paste the token and your chat ID below.' ); ?></p>
				<div style="margin-bottom:6px;">
					<label class="cs-field-label" style="display:block;margin-bottom:3px;"><?php echo esc_html( 'Bot Token' ); ?></label>
					<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">
						<input type="password" id="cs-telegram-token"
						       value="<?php echo esc_attr( $token ); ?>"
						       placeholder="123456789:ABCdefGhI..."
						       autocomplete="off" style="width:100%;max-width:300px;padding:4px 8px;height:32px;">
						<button type="button" id="cs-telegram-token-toggle" class="button" style="height:32px;padding:0 10px;font-size:0.82rem;">
							<?php echo esc_html( 'Show' ); ?>
						</button>
					</div>
				</div>
				<div style="margin-bottom:10px;">
					<label class="cs-field-label" style="display:block;margin-bottom:3px;"><?php echo esc_html( 'Chat ID' ); ?></label>
					<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">
						<input type="password" id="cs-telegram-chat-id"
						       value="<?php echo esc_attr( $chat_id ); ?>"
						       placeholder="-1001234567890"
						       autocomplete="off" style="width:150px;padding:4px 8px;height:32px;">
						<button type="button" id="cs-telegram-chat-toggle" class="button" style="height:32px;padding:0 10px;font-size:0.82rem;">
							<?php echo esc_html( 'Show' ); ?>
						</button>
						<button type="button" id="cs-telegram-fetch-btn" class="button"
						        data-nonce="<?php echo esc_attr( $fetch_nonce ); ?>">
							<?php echo esc_html( 'Fetch Chat ID' ); ?>
						</button>
					</div>
					<span id="cs-telegram-fetch-msg" style="font-size:0.88rem;display:block;margin-top:4px;"></span>
					<p class="cs-help" style="margin-top:4px;"><?php echo esc_html( 'Send any message to your bot on Telegram, then click Fetch Chat ID to auto-fill this field.' ); ?></p>
				</div>
				<div style="display:flex;align-items:center;gap:8px;">
					<button type="button" id="cs-telegram-test-btn" class="button"
					        data-nonce="<?php echo esc_attr( $test_nonce ); ?>"
					        data-source="<?php echo esc_attr( $source ); ?>">
						<?php echo esc_html( 'Send Test' ); ?>
					</button>
					<span id="cs-telegram-test-msg" style="font-size:0.88rem;"></span>
				</div>
			</div>
		</div>
		<?php if ( ! $js_output ) {
			$js_output = true;
			$telegram_settings_js =
				"(function(){\n"
				. "\t['cs-telegram-token','cs-telegram-chat-id'].forEach(function(inputId){\n"
				. "\t\tvar toggleId=inputId==='cs-telegram-token'?'cs-telegram-token-toggle':'cs-telegram-chat-toggle';\n"
				. "\t\tvar inp=document.getElementById(inputId);\n"
				. "\t\tvar btn=document.getElementById(toggleId);\n"
				. "\t\tif(!inp||!btn)return;\n"
				. "\t\tbtn.addEventListener('click',function(){\n"
				. "\t\t\tvar shown=inp.type==='text';\n"
				. "\t\t\tinp.type=shown?'password':'text';\n"
				. "\t\t\tbtn.textContent=shown?'Show':'Hide';\n"
				. "\t\t});\n"
				. "\t});\n"
				. "\tvar fetchBtn=document.getElementById('cs-telegram-fetch-btn');\n"
				. "\tif(fetchBtn){\n"
				. "\t\tfetchBtn.addEventListener('click',function(){\n"
				. "\t\t\tvar btn=this;\n"
				. "\t\t\tvar token=(document.getElementById('cs-telegram-token').value||'').trim();\n"
				. "\t\t\tvar msg=document.getElementById('cs-telegram-fetch-msg');\n"
				. "\t\t\tvar chatIn=document.getElementById('cs-telegram-chat-id');\n"
				. "\t\t\tif(!token){msg.textContent='Enter bot token first.';msg.style.color='#c00';return;}\n"
				. "\t\t\tbtn.disabled=true;\n"
				. "\t\t\tmsg.textContent='Fetching...';msg.style.color='#666';\n"
				. "\t\t\tvar fd=new FormData();\n"
				. "\t\t\tfd.append('action','cloudscale_telegram_fetch_chat_id');\n"
				. "\t\t\tfd.append('nonce',btn.dataset.nonce);\n"
				. "\t\t\tfd.append('telegram_token',token);\n"
				. "\t\t\tfetch(ajaxurl,{method:'POST',body:fd})\n"
				. "\t\t\t\t.then(function(r){return r.json();})\n"
				. "\t\t\t\t.then(function(d){\n"
				. "\t\t\t\t\tif(d.success){chatIn.value=d.data.chat_id;msg.textContent='Chat ID found: '+d.data.chat_id;msg.style.color='#0a5';}\n"
				. "\t\t\t\t\telse{msg.textContent=d.data||'Failed.';msg.style.color='#c00';}\n"
				. "\t\t\t\t})\n"
				. "\t\t\t\t.catch(function(){msg.textContent='Request error.';msg.style.color='#c00';})\n"
				. "\t\t\t\t.finally(function(){btn.disabled=false;});\n"
				. "\t\t});\n"
				. "\t}\n"
				. "\tvar testBtn=document.getElementById('cs-telegram-test-btn');\n"
				. "\tif(testBtn){\n"
				. "\t\ttestBtn.addEventListener('click',function(){\n"
				. "\t\t\tvar btn=this;\n"
				. "\t\t\tvar msg=document.getElementById('cs-telegram-test-msg');\n"
				. "\t\t\tbtn.disabled=true;\n"
				. "\t\t\tif(msg){msg.textContent='Sending...';msg.style.color='#666';}\n"
				. "\t\t\tvar fd=new FormData();\n"
				. "\t\t\tfd.append('action','cloudscale_telegram_test');\n"
				. "\t\t\tfd.append('nonce',btn.dataset.nonce);\n"
				. "\t\t\tfd.append('test_source',btn.dataset.source||'');\n"
				. "\t\t\tfetch(ajaxurl,{method:'POST',body:fd})\n"
				. "\t\t\t\t.then(function(r){return r.json();})\n"
				. "\t\t\t\t.then(function(d){\n"
				. "\t\t\t\t\tif(msg){msg.textContent=d.success?(d.data&&d.data.msg?d.data.msg:'Sent.'):(d.data||'Failed.');msg.style.color=d.success?'#0a5':'#c00';}\n"
				. "\t\t\t\t})\n"
				. "\t\t\t\t.catch(function(){if(msg){msg.textContent='Request error.';msg.style.color='#c00';}})\n"
				. "\t\t\t\t.finally(function(){btn.disabled=false;});\n"
				. "\t\t});\n"
				. "\t}\n"
				. "})();\n";
			// phpcs:ignore WordPress.WP.EnqueuedResourceParameters.NoExplicitVersion -- virtual inline-only handle, no src URL, no cache-busting needed
			wp_register_script( 'cloudscale-telegram-ui', false, array(), false, true );
			wp_add_inline_script( 'cloudscale-telegram-ui', $telegram_settings_js );
			if ( ! wp_script_is( 'cloudscale-telegram-ui', 'enqueued' ) ) {
				wp_enqueue_script( 'cloudscale-telegram-ui' );
			}
		}
	}
}
